var quote = new Array("Every protagonist of every story, show, or movie is the story of my life.", 
	"Intelligence is not a privilege, it's a gift, and you use it for the good of mankind.", 
	"If you wanna win, you gotta fuel like a winner!", 
	"Just Do It!", 
	"That's what she said!", 
	"The SOUL is the warrior's greatest weapon. He closes his eyes and reaches the heavens.", 
	"#sweet!",
	"#Timehop!",
	"#sorry!", 
	"Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live. - @kylerichter", 
	"A man loves his sweetheart the most, his wife the best, but his mother the longest...",
	"No matter what role people play, they will always solve problems everyday. - Dr. Naresh N. Gupta",
	"Rajan life rule no. 383: Turn all your hopes into prayers. Hopes depend on things uncertain. Prayers rely on the only absolute certainty. #God - @MCIronMan",
	"Choose two: Good, Fast, Cheap. - Wexelblat's Scheduling Algorithm",
	"The less code on one line, the less likely you'll encounter a merge conflict.",
	"Lord have mercy upon us, accepting our frail service; mercifully send us blessings, and forgiveness from heavens. - St. Ephrem", 
	"I've always learned more from people who disagree with me.",
	"The next person who calls me a 'nice guy' is going to get punched in the face.",
	"A Church without Youth is a Church without a future. Moreover, Youth without a Church is Youth without a future. - H.H. Pope Shenouda III",
	"Never regret anything because at one time, it was exactly what you wanted.",
	"Why do we fast? Because we fell into sin, in the first place, because we broke the first fast God gave man in the garden from the Tree.",
	"Hyperbole is a thousand times better than exaggeration.",
	"Who the hell cares what anybody else thinks? Just look into your heart and do whatever the hell makes you happy. - Dr. Bob Kelso",
	"Think for yourself. - Immanuel Kant's philosophy of #CriticalThinking!",
	"I have never said that you are not good at what you do. It's just that what you do is not worth doing. - #BigBangTheory!",
	"For everything you have missed, you have gained something else, and for everything you gain, you lose something else. - Ralph Waldo Emerson",
	"Reflecting on how much time I spend thinking about the past or future over what's directly in front of me. - Jack Dorsey",
	"Complicated in the mind, but I'm simple at heart.",
	"A sign of maturity is listening to (and not quickly dismissing) other people's opinions even when they are different than your own.",
	"If you have a difficult task to do, give it to a lazy man, he will find an easier way to do it - Unknown",
	"Before you diagnose yourself with depression or low self-esteem, first make sure that you are not, in fact, just surrounded by assholes.",
	"I’m extremely thankful to my parents for training me to set goals and strive to reach them. - @RyanCarson",
	"As a mobile user, I greatly prefer going to a website rather than installing an app. - Ryan Dahl",
	"When I see a pretty girl, I just wanna go to her and say hi, but I can't because she'll think I'm weird.",
	"If you build your API first and build it well then your quality of life increases as a function of time.",
	"Success isn't doing something well one time, it's doing something well multiple times. It's the difference between luck and skill.",
	"I battled with anger because of all the wrongdoings that have been done to me but now I realize that God wanted more for me. Truly blessed!",
	"Don't come to church after the Nicene Creed has been said. If you aren't here to profess our faith, why come? - Achen",
	"Blessed be the Lord my strength, which teacheth my hands to design, and my fingers to code websites.",
	"You know you love what you do when you wake up every morning excited about what the day brings. I think this is the right field for me!",
	"Guy: Hey, nice to meet you.<br/>Me: Thank you, nice to meet you.<br/>Guy: That's what she said.<br/>Me: (?)",
	"Let people doubt you, when you fulfill your goals you will end up showing people that no one can deter you from your dreams and goals!",
	"A friend is someone who knows you and still likes you. - Nikita",
	"Do something kind today.",
	"This code I just wrote is too magical. I can't figure out what the hell it's doing.",
	"When I saw you I fell in love and you smiled, because you knew. -Shakespeare",
	"When someone says 'You da man!', I truly believe that I am, in fact, da man.",
	"If she's amazing, she won't be easy. If she's easy, she won't be amazing. If she's worth it, you won't give up.",
	"Sometimes me think, 'What is friend?' And then me say, 'Friend is someone to share the last cookie with.' - Cookie Monster",
	"There are two steps to creating change:<br/>1) Figure out where you want to be<br/>2) Figure out how to get there",
	"Nothing is possible if you just believe it isn't. #unwisewords!",
	"Two things define you. Your patience when you have nothing and your attitude when you have everything.",
	"Be selfish: create and build things you want to see. The bet is others want the same.",
	"You know you're in love when you can't fall asleep because reality is finally better than your dreams. - Dr. Seuss",
	"Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring. - Marilyn Monroe",
	"I'm just happy she's happy",
	"Champions are not made of muscle, they are made of heart. When your heart is into something, nothing can stop you!",
	"On this Feast of Dormition, I ask myself: Would a Marthoma quarterback throw a 'Hail Mary?' - Steve Kurian",
	"Making her smile is the way to her heart...or be lazy and just get her food."
);
var q=quote.length, 
    randomQuote=Math.round(Math.random()*(q-1));
document.writeln("<div align='center'>" + quote[randomQuote] + "</div>");
